plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.mta.tehreer.demo'
    compileSdk = 37

    defaultConfig {
        applicationId = "com.mta.tehreer.demo"
        minSdk = 23
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles(getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro')
        }
    }
}

dependencies {
    implementation project(':tehreer-android')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.19.0'
}
