/*
 * Copyright (C) 2026 Muhammad Tayyab Akram
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.mta.tehreer.sfnt

import com.mta.tehreer.collections.FloatList
import com.mta.tehreer.collections.IntList
import com.mta.tehreer.collections.PointList
import com.mta.tehreer.internal.JniBridge
import com.mta.tehreer.internal.collections.FloatBufferList
import com.mta.tehreer.internal.collections.FloatBufferPointList
import com.mta.tehreer.internal.collections.UInt16BufferIntList
import com.mta.tehreer.internal.collections.UIntPtrBufferIntList

/**
 * A `ShapingResult` object is a container for the results of text shaping. It is generated by a
 * `ShapingEngine` object to provide the information related to characters, their glyphs, offsets,
 * and advances.
 */
class ShapingResult {
    private class Finalizable(private val nativeResult: Long) {
        @Suppress("unused")
        protected fun finalize() {
            nDispose(nativeResult)
        }
    }

    internal val nativeResult: Long
    private val finalizable: Finalizable

    internal constructor() {
        nativeResult = nCreate()
        finalizable = Finalizable(nativeResult)
    }

    /**
     * Returns `true` if the text flows backward for this `ShapingResult` object.
     */
    val isBackward: Boolean
        get() = nIsBackward(nativeResult)

    internal val isRTL: Boolean
        get() = nIsRTL(nativeResult)

    /**
     * Returns the index to the first character in source text for this `ShapingResult` object.
     */
    val charStart: Int
        get() = nGetCharStart(nativeResult)

    /**
     * Returns the index after the last character in source text for this `ShapingResult` object.
     */
    val charEnd: Int
        get() = nGetCharEnd(nativeResult)

    private val charCount: Int
        get() = charEnd - charStart

    /**
     * Returns the number of glyphs in this `ShapingResult` object.
     */
    val glyphCount: Int
        get() = nGetGlyphCount(nativeResult)

    /**
     * Returns a list of glyph IDs in this `ShapingResult` object.
     *
     * **Note:** The returned list might exhibit undefined behavior if the `ShapingResult` object is
     * disposed.
     *
     * @return A list of glyph IDs.
     */
    val glyphIds: IntList
        get() = UInt16BufferIntList(this, nGetGlyphIdsPtr(nativeResult), glyphCount)

    /**
     * Returns a list of glyph offsets in this `ShapingResult` object.
     *
     * **Note:** The returned list might exhibit undefined behavior if the `ShapingResult` object is
     * disposed.
     *
     * @return A list of glyph offsets.
     */
    val glyphOffsets: PointList
        get() = FloatBufferPointList(this, nGetGlyphOffsetsPtr(nativeResult), glyphCount)

    /**
     * Returns a list of glyph advances in this `ShapingResult` object.
     *
     * **Note:** The returned list might exhibit undefined behavior if the `ShapingResult` object is
     * disposed.
     *
     * @return A list of glyph advances.
     */
    val glyphAdvances: FloatList
        get() = FloatBufferList(this, nGetGlyphAdvancesPtr(nativeResult), glyphCount)

    /**
     * Returns a list of indexes, mapping each shaped character in source string to corresponding
     * glyph. The list might be empty if no glyph is produced.
     *
     * The map is produced according to following rules.
     *  - If a single character translates into multiple glyphs, then it maps to the first glyph in
     *    the sequence.
     *  - If multiple characters form a group, such as a grapheme, which in turn translates into
     *    multiple glyphs, then each character maps to the first glyph in the sequence.
     *  - If nonconsecutive characters translate to a single glyph or ligature, then each
     *    participating character, and all in-between characters, map to this glyph or ligature.
     *
     * **Note:** The returned list might exhibit undefined behavior if the `ShapingResult` object is
     * disposed.
     *
     * @return A list of indexes, mapping each shaped character in source string to corresponding
     *         glyph.
     */
    val clusterMap: IntList
        get() {
            val pointer = nGetClusterMapPtr(nativeResult)

            return UIntPtrBufferIntList(this, pointer, if (pointer != 0L) charCount else 0)
        }

    /**
     * Returns a list of caret edges having caret stop on every code unit.
     *
     * @return A list of caret edges having caret stop on every code unit.
     */
    fun getCaretEdges(): FloatArray {
        return getCaretEdges(null)
    }

    /**
     * Returns a list of caret edges.
     *
     * @param caretStops An array for caret stops of the code units represented by this object.
     * @return A list of caret edges.
     */
    fun getCaretEdges(caretStops: BooleanArray?): FloatArray {
        require(caretStops == null || caretStops.size >= charCount) {
            "The length of caret stops array must be at least the represented character count"
        }

        return nGetCaretEdges(nativeResult, caretStops)
    }

    override fun toString(): String {
        return "ShapingResult{isBackward=$isBackward" +
            ", charStart=$charStart" +
            ", charEnd=$charEnd" +
            ", glyphCount=$glyphCount" +
            ", glyphIds=$glyphIds" +
            ", glyphOffsets=$glyphOffsets" +
            ", glyphAdvances=$glyphAdvances" +
            ", clusterMap=$clusterMap" +
            "}"
    }

    private external fun nIsBackward(nativeResult: Long): Boolean
    private external fun nIsRTL(nativeResult: Long): Boolean
    private external fun nGetCharStart(nativeResult: Long): Int
    private external fun nGetCharEnd(nativeResult: Long): Int
    private external fun nGetGlyphCount(nativeResult: Long): Int
    private external fun nGetGlyphIdsPtr(nativeResult: Long): Long
    private external fun nGetGlyphOffsetsPtr(nativeResult: Long): Long
    private external fun nGetGlyphAdvancesPtr(nativeResult: Long): Long
    private external fun nGetClusterMapPtr(nativeResult: Long): Long
    private external fun nGetCaretEdges(
        nativeResult: Long, caretStops: BooleanArray?
    ): FloatArray
    companion object {
        init {
            JniBridge.loadLibrary()
        }

        @JvmStatic private external fun nCreate(): Long
        @JvmStatic private external fun nDispose(nativeResult: Long)
    }
}
